<?php

namespace Lumen\AppBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * HistoryBillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryBillRepository extends EntityRepository
{
}
