<?php

namespace Lumen\AppBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * LogBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogBookRepository extends EntityRepository
{
}
