<?php

namespace Lumen\AppBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * QuoteDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteDetailRepository extends EntityRepository
{
}
